// Kaartendata voor Theorie Anatomie 1 (onderste lidmaat) - Thomas More, Y. Bogaerts
// Elke rij: [id, categorie, vraag, antwoord]

window.STUDY_CATEGORIES = [
  { id: "intro",     label: "Skelet - algemene bouw" },
  { id: "term",      label: "Terminologie & bewegingsleer" },
  { id: "gewr",      label: "Gewrichten - algemeen" },
  { id: "spier",     label: "Spieren - algemeen" },
  { id: "zenuw",     label: "Zenuwstelsel - algemeen" },
  { id: "heupbot",   label: "Heup - botten" },
  { id: "heupgew",   label: "Heup - gewricht & ligamenten" },
  { id: "heupspier", label: "Heup - spieren" },
  { id: "heupgait",  label: "Heup - functie & gangcyclus" },
  { id: "kniebot",   label: "Knie - botten" },
  { id: "kniegew",   label: "Knie - gewricht & ligamenten" },
  { id: "kniespier", label: "Knie - spieren" },
  { id: "kniegait",  label: "Knie - functie & gangcyclus" },
  { id: "voetbot",   label: "Enkel/voet - botten" },
  { id: "voetgew",   label: "Enkel/voet - gewrichten" },
  { id: "voetgewelf",label: "Voetgewelf" },
  { id: "voetspier", label: "Enkel/voet - spieren" },
  { id: "voetgait",  label: "Enkel/voet - functie & gangcyclus" },
  { id: "uitlijning",label: "Uitlijning & standsafwijkingen" },
  { id: "zenuwperif",label: "Perifere zenuwen onderste lidmaat" },
];

window.STUDY_CARDS_RAW = [
["c226","intro","Wat is het locomotorisch stelsel?","Het bewegingsapparaat: botten, spieren, gewrichten en een deel van het zenuwstelsel, nodig om een houding aan te nemen of een beweging uit te voeren."],
["c227","intro","In welke 4 categorieen worden botstukken onderverdeeld?","Lange, korte, platte en onregelmatige botstukken."],
["c228","intro","Wat is het periost en wat is de functie ervan?","Het beenvlies dat het bot omhult (behalve het kraakbeen); zorgt voor bescherming, voeding, groei en herstel van botweefsel, en dient als aanhechtingsplaats voor pezen en ligamenten."],
["c229","intro","Wat is de diafyse en de epifyse van een lang botstuk?","De diafyse is de (holle) botschacht, de epifyse is het verbrede uiteinde van het botstuk."],
["c230","intro","Wat bevindt zich in de diafyse van een lang botstuk, en wat is de functie hiervan?","Beenmerg (medulla); speelt een cruciale rol in het immuunsysteem en bij de aanmaak van bloedcellen."],

["c1","term","Wat betekent profundus versus superficialis?","Profundus = diepliggend, superficialis = oppervlakkig liggend."],
["c2","term","Wat betekent dexter versus sinister?","Dexter = rechts, sinister = links (steeds t.o.v. de beschreven persoon)."],
["c3","term","Wat is het verschil tussen cranialis en caudalis?","Cranialis = in de richting van de schedel, caudalis = in de richting van het staartbeen."],
["c4","term","Wat betekent ventralis versus dorsalis?","Ventralis = naar de buikzijde, dorsalis = naar de rugzijde."],
["c5","term","Wat betekent medialis versus lateralis?","Medialis = naar de middellijn toe, lateralis = van de middellijn weg."],
["c6","term","Wat betekent proximalis versus distalis op de ledematen?","Proximalis = dichter bij de romp, distalis = verder naar het uiteinde."],
["c7","term","Wat betekent plantaris versus dorsalis op de voet?","Plantaris = aan de zoolzijde, dorsalis = aan de rugzijde van de voet."],
["c8","term","Wat betekent tibialis versus fibularis als richtingsaanduiding?","Tibialis = naar de tibia toe, fibularis = naar de fibula toe."],
["c9","term","Welke drie hoofdassen worden gebruikt om gewrichtsbewegingen te beschrijven?","De longitudinale as, de transversale as en de sagittale as."],
["c10","term","Rond welke as en in welk vlak verlopen flexie en extensie?","Rond de transversale as, in het sagittale vlak."],
["c11","term","Rond welke as en in welk vlak verlopen abductie en adductie?","Rond de sagittale as, in het frontale vlak."],
["c12","term","Rond welke as en in welk vlak verlopen endo- en exorotatie?","Rond de longitudinale as, in het transversale vlak."],
["c13","term","Wat is het mediane sagittale vlak (mediaanvlak)?","Het vlak dat het lichaam verdeelt in een symmetrische linker en rechter helft."],
["c14","term","Wat verdeelt het frontale (coronale) vlak?","Het lichaam in een voorste en een achterste deel."],
["c15","term","Wat verdeelt het transversale (horizontale) vlak?","Het lichaam in een bovenste en een onderste helft."],
["c16","term","Wat is het verschil tussen flexie en extensie?","Bij flexie verkleint de hoek tussen de gewrichtspartners (buigen), bij extensie vergroot de hoek (strekken)."],
["c17","term","Wat is abductie?","Een beweging van een segment weg van de middenlijn van het lichaam."],
["c18","term","Wat is exorotatie?","Uitwaartse rotatie rond de longitudinale as, waarbij de voorzijde van het segment naar lateraal keert."],
["c19","term","Hoe noemt men de bewegingen van de enkel rond de transversale as?","Plantairflexie en dorsiflexie."],
["c20","term","Wat zijn inversie en eversie van de voet?","Inversie: de zoolzijde keert naar binnen. Eversie: de zoolzijde keert naar buiten."],
["c21","term","Wat zijn anteversie en retroversie van het bekken?","Kantelen van het bekken rond de transversale as: naar voor (anteversie) of naar achter (retroversie)."],
["c22","term","Wat is lateroversie van het bekken?","Kantelen van het bekken rond de sagittale as, naar links of naar rechts."],

["c23","gewr","Wat is een synarthrose?","Een gewricht dat geen beweging toelaat; botstukken rechtstreeks met elkaar vergroeid, met enkel een naad (sutura) zichtbaar."],
["c24","gewr","Wat is een amphiarthrose?","Een gewricht dat zeer beperkte beweging toelaat; botstukken verbonden via kraakbeen (synchondrose) of bindweefsel (symfyse of syndesmose)."],
["c25","gewr","Wat is een diarthrose?","Een synoviaal gewricht dat relatief ruime bewegingen toelaat."],
["c26","gewr","Wat zijn de belangrijkste kenmerken van een synoviaal gewricht?","Een gewrichtsspleet, gewrichtsvlakken bedekt met kraakbeen, een gewrichtskapsel (capsula), en een gewrichtsholte gevuld met synovia (gewrichtsmeer)."],
["c27","gewr","Wat is het verschil tussen de gewrichtskom en de gewrichtskop?","De gewrichtskom (fossa articularis) is hol, de gewrichtskop (caput articulare) is bol."],
["c28","gewr","Wat is het verschil tussen een extern en een intern ligament?","Een extern ligament loopt buiten het gewrichtskapsel, een intern ligament ligt binnen het gewrichtskapsel."],
["c29","gewr","Wat is het verschil tussen meniscus, discus en labrum?","Een discus vult de ruimte tussen twee gewrichtspartners volledig, een meniscus bedekt slechts een deel van het gewrichtsvlak, een labrum vormt een uitbreiding van het gewrichtsvlak."],
["c30","gewr","Wat is een bursa synovialis (slijmbeurs)?","Een afzonderlijk gevormd structuurtje gevuld met synoviaal vocht dat als buffer/wrijvingsverminderaar dient tussen bot en ligamenten of pezen."],
["c31","gewr","Wat is de functie van een corpus adiposum (vetlichaampje) in een gewricht?","Een flexibele opvulling die van vorm verandert tijdens beweging en het kraakbeen beschermt tegen impact van buitenaf."],
["c32","gewr","Hoeveel vrijheidsgraden heeft een enkelassig (uni-axiaal) gewricht, en welke twee types bestaan er?","1 vrijheidsgraad: scharniergewricht (beweging rond de transversale as) en rolgewricht (beweging rond de longitudinale as)."],
["c33","gewr","Welke gewrichtstypes zijn tweeassig (bi-axiaal)?","Ellipsoide en zadelgewrichten; ze laten beweging rond de sagittale en de transversale as toe."],
["c34","gewr","Welk gewrichtstype is drie-assig (tri-axiaal)?","Het bolgewricht (kogelgewricht)."],
["c35","gewr","Wat is een non-axiaal (vlak) gewricht?","Een gewricht zonder echte draaibewegingen, met voornamelijk glijbewegingen (translaties)."],
["c36","gewr","Wat bepaalt, naast de vorm van de gewrichtsvlakken, vooral de bewegingsmogelijkheid van een gewricht?","De positie en spanning van de ligamenten (passieve stabilisatie)."],

["c37","spier","Wat is de origo en de insertio van een spier?","Origo = de pezige oorsprong, insertio = de aanhechting via een pees op het bot."],
["c38","spier","Wat is concentrisch spierwerk?","Spierwerk waarbij de spier bij contractie verkort, zodat oorsprong en aanhechting naar elkaar toe bewegen."],
["c39","spier","Wat is statisch spierwerk?","Spierwerk waarbij er spanning in de spier is, maar geen lengteverandering optreedt."],
["c40","spier","Wat is excentrisch spierwerk?","Spierwerk waarbij de spier spanning opbouwt maar toch uitrekt, omdat een externe kracht groter is dan de spierkracht."],
["c41","spier","Wat zijn het punctum fixum en het punctum mobile?","Punctum fixum = het vaste, stabiele punt (bot dat niet beweegt); punctum mobile (of liberum) = het vrije, bewegende punt."],
["c42","spier","Wat zijn synergisten en antagonisten?","Synergisten zijn spieren met dezelfde functie die samenwerken; antagonisten zijn spieren met een tegengestelde werking."],
["c43","spier","Wat zijn bi-articulaire spieren?","Spieren die twee (of meer) gewrichten overspannen, met een functioneel effect op elk van die gewrichten."],
["c44","spier","M.rectus femoris is bi-articulair: welke functie heeft hij in de heup en welke in de knie?","Flexor van de heup, extensor van de knie."],
["c45","spier","Uit welke bindweefsellagen is een skeletspier opgebouwd, van vezel tot geheel?","Endomysium rond elke spiervezel, perimysium rond de bundels, epimysium rond de hele spier, en fascia rond spiergroepen (compartimenten)."],
["c46","spier","Wat zijn myofibrillen en welke eiwitten bevatten ze?","De contractiele elementen in de spiervezel, opgebouwd uit de eiwitten actine en myosine."],
["c47","spier","Wat is een motorische eenheid?","Alle spiervezels die door eenzelfde motorische zenuwcel worden aangestuurd."],
["c48","spier","Wat is het verschil tussen type I- en type II-spiervezels?","Type I (slow-twitch) trekken langzamer samen; type II (fast-twitch) trekken sneller samen."],
["c49","spier","Wat zijn tonische (houdings)spieren?","Spieren met overwegend type I-vezels, geschikt voor het langdurig handhaven van een statische houding en minder snel vermoeid (bv. m.erector spinae)."],
["c50","spier","Wat zijn fasische (bewegings)spieren?","Spieren met overwegend type II-vezels, gebouwd voor snelle, krachtige dynamische contracties, maar sneller vermoeid."],
["c51","spier","Wat is het pathofysiologisch reactiepatroon bij inactiviteit voor tonische versus fasische spieren?","Tonische spieren neigen te verkorten (contractuur); fasische spieren neigen te atrofieren (volumeverlies)."],
["c52","spier","Hoeveel functionele spiergroepen onderscheidt men rond een drie-assig gewricht?","6 groepen: flexoren, extensoren, adductoren, abductoren, endorotatoren en exorotatoren."],
["c53","spier","Wat meet men met de MRC-schaal en wat is de range?","Spierkracht, op een schaal van 0 tot 5 (Medical Research Council)."],
["c54","spier","Welke drie soorten eindgevoel onderscheidt men bij passief ROM-onderzoek, met telkens een voorbeeld?","Zacht/soft (bv. kniebuiging, weefselbenadering), stevig/firm (bv. buitenwaartse schouderrotatie, kapsel-/ligamentaire rek), hard (bv. elleboogstrekking, bot-op-bot)."],
["c55","spier","Wat betekent een leeg eindgevoel bij ROM-onderzoek?","Er zijn geen structuren meer die de beweging normaal begrenzen; wijst op een ernstig gewrichtsletsel."],

["c56","zenuw","Waaruit bestaat het centraal zenuwstelsel (CZS)?","Hersenen en ruggenmerg."],
["c57","zenuw","Wat omvat het perifeer zenuwstelsel (PZS)?","Al het zenuwweefsel buiten het centraal zenuwstelsel."],
["c58","zenuw","Wat is het verschil tussen afferente en efferente banen?","Afferente banen geleiden sensorische info naar het CZS, efferente banen geleiden motorische impulsen van het CZS naar spieren en organen."],
["c59","zenuw","Wat is het verschil tussen het somatisch en het autonoom zenuwstelsel?","Het somatisch zenuwstelsel zorgt voor willekeurige aansturing van skeletspieren, het autonoom zenuwstelsel voor onwillekeurige aansturing van organen en klieren."],
["c60","zenuw","Uit welke onderdelen bestaat een neuron?","Een cellichaam, dendrieten (korte uitlopers), een axon (lange uitloper) en synapskoppen."],
["c61","zenuw","Wat zijn proprioceptoren?","Receptoren die info geven over de lichaamshouding: positie en beweging van skeletspieren en gewrichten."],
["c62","zenuw","Wat is het verschil tussen sensibele en motorische neuronen?","Sensibele neuronen geven info van zintuigen door naar het CZS (afferent), motorische neuronen geleiden impulsen van het CZS naar effectoren (efferent)."],
["c63","zenuw","Wat is een ganglion?","Een bundeling van cellichamen (grijze stof) in het perifere zenuwstelsel."],
["c64","zenuw","Wat is het verschil tussen sensorische (stijgende) en motorische (dalende) banen in het CZS?","Sensorische banen geleiden info van zintuigen naar centra; motorische banen geleiden info van hersencentra naar de effectoren."],
["c65","zenuw","Wat is de functie van de primaire motorische cortex?","Ze wekt willekeurige bewegingen op door somatische motorische neuronen in hersenstam en ruggenmerg aan te sturen."],
["c66","zenuw","Wat is de functie van de basale kernen?","Onbewuste verwerking van sensorische info en generatie van motorische impulsen; ze reguleren de spiertonus en coordineren aangeleerde bewegingspatronen."],
["c67","zenuw","Tot welk wervelniveau loopt het ruggenmerg?","Tot de eerste/tweede lumbale wervel (L1/L2)."],
["c68","zenuw","Hoeveel ruggenmergsegmenten en spinale zenuwparen zijn er, en hoe zijn ze verdeeld?","31: 8 cervicaal, 12 thoracaal, 5 lumbaal, 5 sacraal en 1 coccygeaal."],
["c69","zenuw","Wat is de cauda equina?","De gemeenschappelijke bundel van spinale zenuwen onder niveau L1/L2, voordat ze het wervelkanaal verlaten."],
["c70","zenuw","Wat bevat de ventrale (anterieure) wortel van een spinale zenuw?","Axonen van motorische neuronen."],
["c71","zenuw","Wat bevat de dorsale (posterieure) wortel van een spinale zenuw?","Sensibele (sensorische) neuronen."],
["c72","zenuw","Wat is het verschil tussen de ramus dorsalis en de ramus ventralis van een spinale zenuw?","De ramus dorsalis bezenuwt rughuid en rugspieren, de ramus ventralis bezenuwt huid en spieren in de rest van het lichaam."],
["c73","zenuw","Wat is een plexus?","Een vlechtwerk gevormd door de rami ventrales van spinale zenuwen, waaruit de perifere zenuwen ontstaan."],
["c74","zenuw","Welke vier plexussen worden onderscheiden?","Plexus cervicalis, plexus brachialis, plexus lumbalis en plexus sacralis."],
["c75","zenuw","Wat is een dermatoom?","Een huidgebied dat hoofdzakelijk door een enkele spinale zenuw van gevoel wordt voorzien."],
["c76","zenuw","Wat is een myotoom?","Een spier of spierdeel dat bezenuwd wordt vanuit eenzelfde spinale zenuw."],
["c77","zenuw","Wat is een kenspier (indicatorspier)?","Een spier die grotendeels door een specifiek spinaal niveau wordt aangestuurd, gebruikt om spinale zenuwletsels te diagnosticeren."],
["c78","zenuw","Wat zijn de klinische kenmerken van een upper motor neuron (UMN)-laesie?","Spasticiteit, hypertonie (verhoogde spiertonus) en hyperreflexie (overdreven reflexen)."],
["c79","zenuw","Wat zijn de klinische kenmerken van een lower motor neuron (LMN)-laesie?","Slappe verlamming, hypotonie, areflexie en snelle spieratrofie."],
["c80","zenuw","Waar kruist (decussatie) de corticospinale baan?","In de hersenstam, ter hoogte van de medulla oblongata."],

["c81","heupbot","Uit welke drie botstukken bestaat het os coxae?","Os ilium, os ischii en os pubis."],
["c82","heupbot","Welke opening wordt begrensd door os pubis en os ischii?","Het foramen obturatum."],
["c83","heupbot","Wat is de SIAS?","De spina iliaca anterior superior."],
["c84","heupbot","Wat is de SIPS?","De spina iliaca posterior superior."],
["c85","heupbot","Welke structuur op het os coxae vormt de heupkom?","Het acetabulum."],
["c86","heupbot","Hoe zijn de twee ossa coxae aan de voorzijde met elkaar verbonden?","Via de symphysis pubica."],
["c87","heupbot","Hoe en met welk botstuk zijn de ossa coxae aan de achterzijde verbonden?","Via het sacroiliacale gewricht, met het sacrum."],
["c88","heupbot","Wat voor type verbindingen zijn de sacroiliacale gewrichten en de symphysis pubica?","Amphiarthrosen; ze laten zeer weinig beweging toe."],
["c89","heupbot","Wat is het caput femoris?","De kop van het femur (proximale epifyse) die samen met het acetabulum het heupgewricht vormt."],
["c90","heupbot","Wat is het verschil in ligging tussen trochanter major en trochanter minor?","Trochanter major ligt lateraal, trochanter minor ligt mediaal; beide liggen onder de femurhals."],
["c91","heupbot","Hoe heet de botkam aan de achterzijde tussen trochanter major en minor, en hoe heet de verbinding aan de voorzijde?","Achteraan: crista intertrochanterica. Vooraan: linea intertrochanterica."],

["c92","heupgew","Wat voor type gewricht is het heupgewricht (articulatio coxae)?","Een drie-assig bolgewricht, tussen caput femoris en acetabulum."],
["c93","heupgew","Wat is de functie van het labrum acetabulare?","Het verdiept de heupkom, waardoor de stabiliteit van het heupgewricht vergroot wordt."],
["c94","heupgew","Welke ligamenten liggen aan de voorzijde van het heupgewricht?","Het (tweedelige) iliofemorale ligament en het pubofemorale ligament, samen Z-vormig."],
["c95","heupgew","Welk ligament ligt aan de achterzijde van het heupgewricht?","Het ischiofemorale ligament."],
["c96","heupgew","Hoe beinvloeden de schroefvormige heupligamenten de stabiliteit bij extensie versus flexie?","Bij extensie spannen ze op, wat de stabiliteit vergroot; bij flexie ontspannen ze, wat meer beweging toelaat."],
["c97","heupgew","Welk ligament limiteert vooral de heupabductie?","Het lig. pubofemorale."],
["c98","heupgew","Welk ligament limiteert de heupadductie, en tot ongeveer hoeveel graden?","Het laterale deel van het lig. iliofemorale, tot ongeveer 30 graden."],
["c99","heupgew","Waardoor wordt de heupflexie-amplitude vooral beperkt?","Door de spierspanning in de (biarticulaire) hamstrings, de heupextensoren."],
["c100","heupgew","Tot ongeveer hoeveel graden wordt heupextensie ligamentair gelimiteerd bij een gestrekte knie?","Ongeveer 20 graden."],
["c101","heupgew","Welke ligamenten limiteren respectievelijk endorotatie en exorotatie van de heup?","Endorotatie wordt gelimiteerd door de achterste ligamenten, exorotatie door de ventrale ligamenten."],

["c102","heupspier","Noem de belangrijkste heupflexoren.","M.psoas major, m.iliacus (samen m.iliopsoas), m.sartorius en m.rectus femoris."],
["c103","heupspier","Noem de belangrijkste heupextensoren.","M.gluteus maximus en de hamstrings: m.semitendinosus, m.semimembranosus en m.biceps femoris."],
["c104","heupspier","Noem de belangrijkste heupabductoren.","M.gluteus medius en m.gluteus minimus."],
["c105","heupspier","Wat is de tractus iliotibialis en wat is zijn functie?","Een bindweefselige band tussen ilium en tibia, aanhechtingsplaats van m.tensor fasciae latae en delen van m.gluteus maximus; biedt zijdelingse stabiliteit aan heup en knie."],
["c106","heupspier","Wat is het tractus iliotibialis frictiesyndroom?","Irritatie van de tractus iliotibialis door schuren over de laterale femurcondyle bij het buigen en strekken van de knie, vooral bij sporters."],
["c107","heupspier","Welke spier is de belangrijkste heupendorotator?","M.gluteus minimus."],
["c108","heupspier","Welke bijkomende functie hebben de bovenste en onderste helft van m.gluteus maximus?","De bovenste helft werkt vooral als abductor, de onderste helft eerder als adductor (naast de exorotatiefunctie van de hele spier)."],
["c109","heupspier","Welke bijkomende functie hebben de hamstrings, naast heupextensie?","Knieflexie."],
["c110","heupspier","Welke bijkomende functie hebben m.iliopsoas en m.sartorius, naast heupflexie?","Exorotatie van de heup."],
["c111","heupspier","Welke functie heeft m.rectus femoris ter hoogte van de knie?","Knie-extensie (het is een bi-articulaire spier: heupflexor en knie-extensor)."],

["c112","heupgait","Welke spiergroep is vooral actief tijdens de zwaaifase om het been vooruit te brengen, en hoe?","De heupflexoren, met concentrisch spierwerk."],
["c113","heupgait","Welke spiergroep remt de zwaaibeweging van het been af aan het einde van de zwaaifase, en hoe?","De heupextensoren, met excentrisch spierwerk."],
["c114","heupgait","Welke spiergroep zorgt voor voorwaartse propulsie tijdens de steunfase (heup), en hoe?","De heupextensoren, met concentrisch spierwerk."],
["c115","heupgait","Wat is de unipodale steunfase?","Het deel van de steunfase waarop slechts een been de grond raakt."],
["c116","heupgait","Wat is een Trendelenburg-gang en welke spieren zijn hierbij verzwakt?","Een gangafwijking waarbij het bekken tijdens het stappen wegzakt (niet horizontaal blijft) naar de niet-ondersteunde kant, door verzwakte heupabductoren."],
["c117","heupgait","Wat is de functie van de heupendorotatoren in het gangpatroon?","Ze vergroten de staplengte doordat ze tijdens de standfase het bekken naar voren trekken (rotatie), zodat het zwaaiende been een grotere stap kan maken."],
["c118","heupgait","Wat doen de heupexorotatoren net na het hielcontact (heel strike)?","Ze remmen excentrisch de natuurlijke neiging van het bovenbeen af om ongecontroleerd naar binnen te draaien, en beschermen zo de knie."],

["c119","kniebot","Welke twee structuren op het distale femur zijn bedekt met kraakbeen?","De condylus medialis en de condylus lateralis."],
["c120","kniebot","Wat is de facies patellaris?","Het contactvlak aan de voorzijde van het femur, waar beide condylen in elkaar overlopen, bestemd voor de knieschijf."],
["c121","kniebot","Welke structuur scheidt de condylen aan de achterzijde van het femur?","De fossa intercondylaris."],
["c122","kniebot","Wat is het tibiaplateau?","Het proximale, dragende vlak van de tibia dat de femurcondylen ondersteunt."],
["c123","kniebot","Wat is de tuberositas tibiae en waarvoor dient ze?","Een botuitsteeksel aan de voorzijde onder het tibiaplateau; belangrijke aanhechtingsplaats voor de quadricepspees (ligamentum patellae)."],
["c124","kniebot","Waar maakt het caput fibulae contact met de tibia?","Latero-posterieur, onder de laterale tibiacondyle."],
["c125","kniebot","Uit welke delen bestaat de patella?","De basis (bovenrand, afgevlakt), de apex (onderrand, spits), de facies anterior (ventraal, vlak) en de facies articularis (dorsaal, bedekt met kraakbeen)."],

["c126","kniegew","Uit welke twee deelgewrichten bestaat het articulatio genus (kniegewricht)?","Het tibiofemorale gewricht en het patellofemorale gewricht."],
["c127","kniegew","Is de fibula betrokken bij het kniegewricht?","Nee."],
["c128","kniegew","Wat is de functie van de patella?","Ze voorkomt dat de quadricepspees bekneld raakt in de gewrichtsspleet, en vergroot de hefboom (momentarm) van de m.quadriceps."],
["c129","kniegew","Welke ligamenten stabiliseren de knie zijdelings, en zijn ze intra- of extracapsulair?","Het mediaal en lateraal collateraal ligament; ze zijn extracapsulair."],
["c130","kniegew","Welke ligamenten liggen intracapsulair in de knie, en wat is hun functie?","De voorste en achterste kruisband (lig. cruciatum anterius en posterius); ze voorkomen dat de femurcondylen van het tibiaplateau afrollen en stabiliseren de knie in het sagittale vlak."],
["c131","kniegew","Waar hecht het ligamentum patellae aan?","Op de tuberositas tibiae."],
["c132","kniegew","Wat is de functie van de menisci in de knie?","Ze vergroten de congruentie tussen femurcondylen en tibiaplateau en zorgen voor schokabsorptie."],
["c133","kniegew","Hoeveel graden knieflexie en hoeveel graden hyperextensie zijn normaal mogelijk?","Ongeveer 150 graden flexie en 5-10 graden hyperextensie."],
["c134","kniegew","Waardoor wordt de knie-extensie vanuit neutrale stand gelimiteerd?","Door de dorsale knieligamenten."],
["c135","kniegew","Waardoor wordt de knieflexie-amplitude vooral bepaald (niet ligamentair)?","Door de lengte van de biarticulaire m.quadriceps, die afhankelijk is van de stand van de heup."],
["c136","kniegew","Is endo- of exorotatie van de knie mogelijk bij volledige extensie?","Nee, dit wordt volledig geblokkeerd door spanning op de collaterale ligamenten; pas mogelijk bij een gebogen knie."],
["c137","kniegew","Wat is de slotrotatie van de knie?","Aan het einde van de extensiebeweging draait het onderbeen enkele graden naar buiten, zodat de gewrichtsvlakken van femur en tibia optimaal op elkaar passen."],

["c138","kniespier","Noem de drie hamstrings (knieflexoren).","M.biceps femoris, m.semimembranosus en m.semitendinosus."],
["c139","kniespier","Uit welke vier delen bestaat de m.quadriceps femoris?","M.rectus femoris, vastus lateralis, vastus medialis en vastus intermedius."],
["c140","kniespier","Welk deel van de quadriceps is bi-articulair, en welke extra functie heeft het?","M.rectus femoris; het is ook een heupflexor."],
["c141","kniespier","Welke spier zorgt voor knie-exorotatie?","M.biceps femoris (de laterale hamstring)."],
["c142","kniespier","Welke spieren zorgen voor knie-endorotatie?","M.semimembranosus en m.semitendinosus (de mediale hamstrings)."],

["c143","kniegait","Wat gebeurt er met de knie aan het begin van de steunfase, en waarom?","Een korte flexie (afgeremd excentrisch door de extensoren), onmiddellijk gevolgd door strekking (concentrisch), om de verticale verplaatsing van het zwaartepunt te minimaliseren."],
["c144","kniegait","Welke spiergroep werkt vooral excentrisch bij het afgaan van een trap?","De knie-extensoren (quadriceps)."],
["c145","kniegait","Zijn de quadriceps of de hamstrings doorgaans sterker?","De quadriceps (extensoren) zijn beduidend sterker dan de hamstrings."],

["c146","voetbot","Waardoor zijn tibia en fibula over hun volledige lengte met elkaar verbonden?","Door de membrana interossea."],
["c147","voetbot","Hoe heten de binnen- en de buitenenkel?","Malleolus medialis (op de tibia, binnenzijde) en malleolus lateralis (op de fibula, buitenzijde)."],
["c148","voetbot","Wat is de malleolusvork?","De gewrichtskom gevormd door de distale tibia en fibula samen, voor het enkelgewricht."],
["c149","voetbot","Uit hoeveel botstukjes bestaat het voetskelet?","26."],
["c150","voetbot","Welke drie delen worden onderscheiden in het voetskelet?","De tarsus (voetwortel), de metatarsus (middenvoet) en de ossa digitorum (tenen)."],
["c151","voetbot","Welke zeven botten vormen de tarsus?","Talus, calcaneus, os naviculare, os cuboideum, os cuneiforme mediale, os cuneiforme intermedium en os cuneiforme laterale."],
["c152","voetbot","Welk bot vormt samen met tibia en fibula het bovenste spronggewricht?","De talus."],
["c153","voetbot","Welk bot ondersteunt de talus?","De calcaneus (hielbeen)."],
["c154","voetbot","Wat is het sustentaculum tali?","Een naar mediaal uitstekende structuur op de calcaneus, met een gewrichtsvlak voor de talus."],
["c155","voetbot","Wat is de tuber calcanei en waarvoor is deze belangrijk?","De posterieure botmassa van de calcaneus (de hiel); belangrijke aanhechtingsplaats voor de achillespees."],
["c156","voetbot","Hoeveel ossa metatarsi zijn er en hoe worden ze genummerd?","5, genummerd van I (mediaal) tot V (lateraal)."],
["c157","voetbot","Uit welke drie delen bestaat een os metatarsale?","Basis, corpus en caput."],
["c158","voetbot","Hoeveel phalanges heeft de hallux, en hoeveel de andere tenen?","De hallux heeft 2 phalanges; digiti II tot V hebben elk 3 phalanges (proximalis, media en distalis)."],

["c159","voetgew","Welke botstukken vormen het bovenste spronggewricht (articulatio talocruralis)?","De distale tibia en fibula samen met de talus."],
["c160","voetgew","Op hoeveel manieren zijn tibia en fibula met elkaar verbonden?","Drie: proximaal via de articulatio tibiofibularis, over de volledige lengte via de membrana interossea, en distaal via de syndesmosis tibiofibularis."],
["c161","voetgew","Wat is het ligamentum deltoideum en uit welke delen bestaat het?","Het mediale ligament van het talocrurale gewricht, bestaande uit 4 delen: pars tibiotalaris anterior, pars tibiotalaris posterior, pars tibionavicularis en pars tibiocalcanea."],
["c162","voetgew","Welke drie ligamenten vormen de laterale band van het talocrurale gewricht?","Lig. talofibulare anterius, lig. talofibulare posterius en lig. calcaneofibulare."],
["c163","voetgew","Uit welke twee deelgewrichten bestaat het onderste spronggewricht (articulatio talotarsalis)?","Het art. subtalaris (achteraan, tussen talus en calcaneus) en het art. talocalcaneonavicularis (vooraan, tussen talus, calcaneus en os naviculare)."],
["c164","voetgew","Rond welk soort as beweegt het onderste spronggewricht, en welke bewegingen levert dit op?","Rond een schuine as (van postero-latero-caudaal naar antero-medio-craniaal); dit levert inversie en eversie op."],
["c165","voetgew","Welke gewrichten vormen samen de gewrichtslijn van Chopart?","De art. calcaneocuboidea en de art. talonaviculare."],
["c166","voetgew","Wat scheidt de gewrichtslijn van Chopart functioneel?","De achtervoet van de middenvoet."],
["c167","voetgew","Wat is de gewrichtslijn van Lisfranc?","De lijn gevormd door alle tarsometatarsale gewrichten."],
["c168","voetgew","Wat zijn pronatie en supinatie van de voet?","Bewegingen van midden- en voorvoet ten opzichte van de achtervoet, rond een as via calcaneus, os naviculare en de 2de voetstraal."],
["c169","voetgew","Welke bewegingscombinaties treden functioneel meestal samen op in de voet?","Inversie gaat meestal samen met supinatie, eversie meestal met pronatie."],
["c170","voetgew","Wat betekenen de afkortingen MTP, PIP en DIP?","Metatarsophalangeaal gewricht, proximaal interphalangeaal gewricht en distaal interphalangeaal gewricht."],
["c171","voetgew","Hoeveel interphalangeale (IP) gewrichten heeft de hallux?","Slechts 1."],
["c172","voetgew","Waardoor wordt de dorsiflexie van de enkel gelimiteerd?","Door het voorste deel van de talus dat tegen de tibia botst, de posterieure ligamenten, en de spanning in de plantairflexoren."],
["c173","voetgew","Waardoor wordt de plantaire flexie van de enkel gelimiteerd?","Door het posterieure deel van de talus dat tegen het gewrichtsvlak botst, de anterieure ligamenten, en de spanning in de dorsiflexoren."],

["c174","voetgewelf","Wat zijn de drie ossale steunpunten van de voetzool?","Het caput van metatarsaal I, het caput van metatarsaal V, en de tuber calcanei."],
["c175","voetgewelf","Welk bot vormt het toppunt van de mediale voetboog, en hoe hoog boven de grond ligt dit?","Het os naviculare, 15-18 mm boven de grond."],
["c176","voetgewelf","Welk metatarsale vormt het hoogste punt van de transversale boog, en hoe hoog is dit ongeveer?","Metatarsaal II, ongeveer 9 mm."],
["c177","voetgewelf","Welke structuur ondersteunt passief het longitudinale gewelf, tussen tuber calcanei en de metatarsaalkoppen?","De aponeurosis plantaris (fascia plantaris)."],
["c178","voetgewelf","Welke spieren ondersteunen actief het longitudinale voetgewelf?","De korte voetspieren, m.flexor hallucis longus, m.flexor digitorum longus en m.tibialis posterior."],
["c179","voetgewelf","Welk ligament ondersteunt passief de dwarse (transversale) boog?","Het lig. metatarsale transversum profundum."],
["c180","voetgewelf","Wat zijn de drie functies van de voetgewelven?","Verdeling van inwerkende krachten, schokabsorptie (veerfunctie) en adaptatie aan oneffen ondergrond."],

["c181","voetspier","Uit welke drie spieren bestaat de m.triceps surae?","M.gastrocnemius, m.plantaris en m.soleus."],
["c182","voetspier","Waar hecht de m.triceps surae gemeenschappelijk aan?","Via de achillespees op de calcaneus."],
["c183","voetspier","Noem de dieper gelegen plantairflexoren van de enkel.","M.flexor digitorum longus, m.flexor hallucis longus, m.tibialis posterior, m.peroneus longus en m.peroneus brevis."],
["c184","voetspier","Noem de dorsiflexoren van de enkel.","M.tibialis anterior, m.extensor digitorum longus en m.extensor hallucis longus."],
["c185","voetspier","Welke spieren zijn de belangrijkste evertoren van de voet?","M.peroneus longus en m.peroneus brevis."],
["c186","voetspier","Noem de belangrijkste invertoren van de voet.","M.tibialis anterior, m.tibialis posterior, m.flexor digitorum longus, m.flexor hallucis longus, en ook de m.triceps surae."],
["c187","voetspier","Welke spieren zijn teenflexoren?","M.flexor digitorum longus, m.flexor digitorum brevis, m.flexor hallucis longus en m.flexor hallucis brevis."],
["c188","voetspier","Welke spieren zijn teenextensoren?","M.extensor digitorum longus, m.extensor digitorum brevis, m.extensor hallucis longus en m.extensor hallucis brevis."],
["c189","voetspier","Wat zijn intrinsieke voetspieren en wat is hun functie?","Spieren met zowel hun oorsprong als hun aanhechting binnen de voet; ze stabiliseren de voetbogen, verzorgen fijne teenbewegingen en passen de voet aan oneffen ondergrond aan."],

["c190","voetgait","Welke spiergroep is het belangrijkst voor postural sway (evenwicht bij stilstaan)?","De plantairflexoren."],
["c191","voetgait","Wat is pes equinus en welke spiergroep-verkorting veroorzaakt dit?","Een spitsvoet (te veel plantairflexie-stand), veroorzaakt door verkorting van de plantairflexoren."],
["c192","voetgait","Wat is een equinovarus-stand, en waardoor ontstaat die?","Een spitsvoet gecombineerd met inversie, doordat de m.triceps surae mediaal van de subtalaire as aanhecht en dus ook een inversiefunctie heeft."],
["c193","voetgait","Wat is het verschil tussen een klapvoet en een dropvoet?","Klapvoet: onvoldoende kracht om de voet na hielcontact excentrisch af te remmen, waardoor de voet neerklapt. Dropvoet: de dorsiflexoren zijn zo verzwakt dat ze zelfs het gewicht van de voet niet kunnen opheffen, waardoor de voet in de zwaaifase afhangt."],
["c194","voetgait","Wat is foot clearance en welke spiergroep zorgt hiervoor?","Ervoor zorgen dat de tenen niet over de grond slepen tijdens de zwaaifase; verzorgd door concentrische activiteit van de dorsiflexoren (voetheffers)."],
["c195","voetgait","Welke bewegingsvolgorde maakt de achtervoet tijdens de steunfase?","Eerst eversie, daarna inversie."],

["c196","uitlijning","Wat is de Mikulicz-lijn?","De mechanische as van het been, van het centrum van de heupkop naar het centrum van het bovenste spronggewricht."],
["c197","uitlijning","Wat is de normale femurhalshoek (collum-diafysehoek) bij volwassenen?","126 graden (coxa norma)."],
["c198","uitlijning","Wat zijn coxa vara en coxa valga?","Coxa vara = een kleinere femurhalshoek dan normaal, coxa valga = een grotere femurhalshoek dan normaal (126 graden)."],
["c199","uitlijning","Wat is de normale tibiofemorale hoek, en hoe noemt men dit?","174 graden; dit heet fysiologische valgus."],
["c200","uitlijning","Wat is genu varum?","Een tibiofemorale hoek groter dan 174 graden (o-benen); geeft hogere compressie mediaal in de knie."],
["c201","uitlijning","Wat is genu valgum?","Een tibiofemorale hoek kleiner dan 174 graden (x-benen); geeft hogere compressie lateraal in de knie."],
["c202","uitlijning","Wat zijn pes valgus en pes varus?","Afwijkingen in de uitlijning van de achtervoet t.o.v. de tibia-as in het frontale vlak (hoek kleiner dan 180 graden lateraal = valgus, mediaal = varus)."],
["c203","uitlijning","Wat is genu recurvatum?","Een hyperextensiestand van de knie in het sagittale vlak."],
["c204","uitlijning","Wat is genu antecurvatum?","Een afwijkende flexiestand van de knie in het sagittale vlak."],
["c205","uitlijning","Wat is een plantigrade stand van de enkel?","De neutrale stand waarbij het onderbeen loodrecht (90 graden) op de voetzool staat."],
["c206","uitlijning","Wat is het verschil tussen pes equinus en pes calcaneus in het sagittale vlak?","Pes equinus = te veel plantairflexie-stand, pes calcaneus = te veel dorsiflexie-stand."],
["c207","uitlijning","Wat is de normale antetorsiehoek van de femur, en wat is coxa antetorta?","Normaal ongeveer 12 graden; coxa antetorta is een grotere antetorsiehoek, waarbij de knie meer naar binnen wijst."],
["c208","uitlijning","Wat is coxa retrotorta?","Een kleinere antetorsiehoek dan normaal, waarbij de knie meer naar buiten wijst."],
["c209","uitlijning","Wat is de tibiale torsiehoek en hoeveel graden bedraagt deze ongeveer?","De hoek tussen de dwarsas door het tibiaplateau en de dwarsas door de enkelvork; ongeveer 23 graden."],
["c210","uitlijning","Wat is metatarsus adductus?","Wanneer metatarsaal II naar mediaal devieert ten opzichte van de calcaneus-as."],
["c211","uitlijning","Wat is pes cavus?","Een versterkte voetwelving (holvoet)."],
["c212","uitlijning","Wat is pes planus?","Verlies van de lengtewelving (platvoet)."],
["c213","uitlijning","Wat is pes transversoplanus?","Verlies van de dwarswelving (spreidvoet)."],

["c214","zenuwperif","Uit welke twee plexussen komen de perifere zenuwen van het onderste lidmaat?","De plexus lumbalis (L1-L4) en de plexus sacralis (L5-S4)."],
["c215","zenuwperif","Welke twee belangrijke perifere zenuwen komen uit de plexus lumbalis?","De n.femoralis en de n.obturatorius."],
["c216","zenuwperif","Welke spieren bezenuwt de n.femoralis, en wat is de functie-uitval bij letsel?","M.iliopsoas en m.quadriceps femoris; uitval geeft verlies van heupflexie en knie-extensie."],
["c217","zenuwperif","Welke spieren bezenuwt de n.obturatorius, en wat is de functie-uitval bij letsel?","De heupadductoren; uitval geeft verlies van heupadductie."],
["c218","zenuwperif","Welke spieren bezenuwt de n.gluteus superior, en wat is de functie-uitval bij letsel?","M.gluteus medius, m.gluteus minimus en m.tensor fasciae latae; uitval geeft verlies van heupabductie."],
["c219","zenuwperif","Welke spier bezenuwt de n.gluteus inferior, en wat is de functie-uitval bij letsel?","M.gluteus maximus; uitval geeft verlies van heupextensie."],
["c220","zenuwperif","Welke spieren bezenuwt de n.ischiadicus rechtstreeks, en wat is de functie-uitval bij letsel?","De hamstrings; uitval geeft verlies van knieflexie."],
["c221","zenuwperif","Wat is de n.ischiadicus, en waar splitst hij zich in twee takken?","De dikste zenuw van het lichaam; hij splitst zich ter hoogte van de fossa poplitea (kniekuil) in de n.fibularis communis en de n.tibialis."],
["c222","zenuwperif","Welke functie-uitval geeft schade aan de n.fibularis (communis, superficialis of profundus)?","Verlies van eversie en dorsiflexie."],
["c223","zenuwperif","Welke functie-uitval geeft schade aan de n.tibialis?","Verlies van plantairflexie en inversie."],
["c224","zenuwperif","Uit welke spinale segmenten ontstaan de n.femoralis en de n.obturatorius?","L2 tot L4."],
["c225","zenuwperif","Uit welke spinale segmenten ontstaat de n.ischiadicus?","L4 tot S3."],
];

window.STUDY_CARDS = window.STUDY_CARDS_RAW.map(function(row) {
  return { id: row[0], cat: row[1], q: row[2], a: row[3] };
});
